import Navbar from "@/components/Navbar";
import "./globals.css";
import { Work_Sans } from "next/font/google";
import Footer from "@/components/Footer";

const work_sans = Work_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${work_sans.className} flex flex-col justify-between min-h-screen`}
      >
        <Navbar />
        <main className="w-full h-full flex-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
